plugins {
    id 'com.android.application'
}

android {
    namespace 'com.qandilalzman.digital'
    compileSdk 34

    defaultConfig {
        applicationId "com.qandilalzman.digital"
        minSdk 21
        targetSdk 34
        versionCode 30
        versionName "3.30.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core:1.12.0'
}
